"""empty message

Revision ID: 1d2a94031fe9
Revises: 286089a6c460
Create Date: 2022-01-17 18:52:14.667700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2a94031fe9'
down_revision = '286089a6c460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
