"""empty message

Revision ID: 286089a6c460
Revises: b6cbdef2b470
Create Date: 2022-01-17 18:45:02.098478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286089a6c460'
down_revision = 'b6cbdef2b470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
