"""empty message

Revision ID: 6bddf5114965
Revises: 1d2a94031fe9
Create Date: 2022-01-17 18:53:20.464025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bddf5114965'
down_revision = '1d2a94031fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
