"""empty message

Revision ID: 87ae4d721173
Revises: 2807edd385a2
Create Date: 2022-01-13 10:58:56.745997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ae4d721173'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
