"""empty message

Revision ID: e2e6c3344a33
Revises: 2972629cd0e3
Create Date: 2022-01-23 17:50:29.931301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e6c3344a33'
down_revision = '2972629cd0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_request', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('password_request', sa.String(length=80), nullable=False))
    op.drop_column('user', 'email')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('user', 'password_request')
    op.drop_column('user', 'email_request')
    # ### end Alembic commands ###
